name: ai_lab
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.9.23
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.3
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.9.25
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pywin32=311
  - pyzmq=27.0.2
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.2
      - filelock==3.14.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - munkres==1.1.4
      - narwhals==2.13.0
      - networkx==3.2.1
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.4.0
      - protobuf==6.33.2
      - pyarrow==21.0.0
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - pytz==2023.4
      - pyyaml==6.0.3
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.28.2
      - rich==13.4.2
      - rpds-py==0.27.1
      - scipy==1.13.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - smmap==5.0.2
      - soupsieve==2.8
      - streamlit==1.50.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - toml==0.10.2
      - tomli==2.3.0
      - tqdm==4.65.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - watchdog==6.0.0
      - xtcocotools==1.14.3
      - yapf==0.43.0
prefix: C:\Users\GIGABYTE\miniconda3\envs\ai_lab
